# Generated by Django 2.2.7 on 2019-12-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=11)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32)),
                ('wxopenid', models.CharField(blank=True, db_column='wxOpenid', max_length=25, null=True)),
                ('create_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
    ]
