# Generated by Django 2.2.7 on 2019-12-02 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShareToWin', '0002_auto_20191202_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
